# Generated by Django 4.0.3 on 2022-03-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longurl', models.URLField()),
                ('shorturl', models.CharField(blank=True, max_length=20, unique=True)),
            ],
        ),
    ]
